# Generated by Django 3.2.6 on 2021-08-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='dummy-1', unique=True),
            preserve_default=False,
        ),
    ]
